version: '3.5'
services:
  dashdot:
    container_name: dashdot
    image: mauricenino/dashdot:latest
    restart: on-failure
    privileged: true
    ports:
      - 3001:3001
    volumes:
      - /:/mnt/host:ro
    environment:
      DASHDOT_ENABLE_CPU_TEMPS: "true"
      DASHDOT_ENABLE_STORAGE_SPLIT_VIEW: "true"
    networks:
      - DOCKER_NETWORK

networks:
  DOCKER_NETWORK:
    external: true
    name: ${DOCKER_NETWORK}