version: '3'
services:
  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    restart: on-failure
    ports:
      - 5055:5055
    volumes:
      - ./container-data/config:/app/config:z
    environment:
      TZ: ${TZ}
    networks:
      - DOCKER_NETWORK

networks:
  DOCKER_NETWORK:
    external: true
    name: ${DOCKER_NETWORK}