version: '3.3'
services:
  sftpgo:
    container_name: sftpgo
    image: ghcr.io/drakkan/sftpgo:latest
    restart: on-failure
    ports:
      - '8090:8090'
      - '2022:2022'
      - '10080:10080'
    volumes:
      - ./container-data/home:/var/lib/sftpgo:z
      - ./container-data/data:/srv/sftpgo:z
      - ${MEDIA_DIR}:/data:z
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      UMASK: 002
      SFTPGO_HTTPD__BINDINGS__0__PORT: 8090
      SFTPGO_WEBDAVD__BINDINGS__0__PORT: 10080
    networks:
      - DOCKER_NETWORK

networks:
  DOCKER_NETWORK:
    external: true
    name: ${DOCKER_NETWORK}