version: '3'
services:
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr:latest
    restart: on-failure
    ports:
      - 9696:9696
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./container-data/config:/config:z
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      UMASK: 002
    networks:
      - DOCKER_NETWORK

networks:
  DOCKER_NETWORK:
    external: true
    name: ${DOCKER_NETWORK}